name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: sudo apt install nasm
    - name: Build
      run: make all
    - uses: actions/upload-artifact@v3
      with:
        name: Output
        path: output
